apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.configCmName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spiderpool.spiderpoolController.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  conf.yml: |
    ipamUnixSocketPath: {{ .Values.configmap.config.ipamUnixSocketPath }}
    networkMode: {{ .Values.configmap.config.networkMode }}
    enableIPv4: {{ .Values.ipFamily.enableIPv4 }}
    enableIPv6: {{ .Values.ipFamily.enableIPv6 }}
    clusterDefaultIPv4IPPool: [{{ .Values.clusterDefaultPool.ipv4IPPoolName }}]
    clusterDefaultIPv6IPPool: [{{ .Values.clusterDefaultPool.ipv6IPPoolName }}]
