apiVersion: spiderpool.spidernet.io/v1
kind: SpiderIPPool
metadata:
  name: use-excludeips
spec:
  ipVersion: 4
  subnet: 172.18.40.0/24
  ips:
    - 172.18.40.40-172.18.40.50
  excludeIPs:
    - 172.18.40.45
