name: Auto Clean ImageCI

on:
  schedule:
    # Run the GC at 3am once for a week
    - cron: "0 3 * * 6"
  workflow_dispatch:

jobs:
  prune-controller-ci:
    uses: ./.github/workflows/call-clean-ghcr.yaml
    with:
      image_name: spiderpool-controller-ci
      older_than: "2"

  prune-agent-ci:
    uses: ./.github/workflows/call-clean-ghcr.yaml
    with:
      image_name: spiderpool-agent-ci
      older_than: "2"

  prune-controller-beta:
    uses: ./.github/workflows/call-clean-ghcr.yaml
    with:
      image_name: spiderpool-controller-beta
      older_than: "2"

  prune-agent-beta:
    uses: ./.github/workflows/call-clean-ghcr.yaml
    with:
      image_name: spiderpool-agent-beta
      older_than: "2"
