name: Auto Nightly CI

permissions: write-all

on:
  schedule:
    # each day
    - cron: "0 20 * * *"
  push:
    branches:
      - main
      - release-*

jobs:
  run-ci:
    uses: ./.github/workflows/call-ci.yaml
    secrets: inherit
